[tool.ruff]
target-version = "py312"
include = ["aligner/app"]

[tool.basedpyright]
include = ["aligner/app/**.py"]
reportMissingImports = "error"
reportMissingTypeStubs = false
reportUnusedCallResult = false
pythonVersion = "3.12"
typeCheckingMode = "recommended"
allowedUntypedLibraries = ["soundfile"]
venvPath = "aligner"
venv=".venv"
