/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedTestImport } from './routes/_protected/test'
import { Route as ProtectedSettingsImport } from './routes/_protected/settings'
import { Route as ProtectedFocusSessionImport } from './routes/_protected/focus-session'
import { Route as ProtectedDemoImport } from './routes/_protected/demo'
import { Route as ProtectedDashboardImport } from './routes/_protected/dashboard'
import { Route as ProtectedCollectionImport } from './routes/_protected/collection'
import { Route as AuthSignUpImport } from './routes/_auth/sign-up'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'
import { Route as ProtectedClassroomsIndexImport } from './routes/_protected/classrooms/index'
import { Route as ProtectedChaptersIndexImport } from './routes/_protected/chapters/index'
import { Route as ProtectedClassroomsClassroomIdRouteImport } from './routes/_protected/classrooms/$classroomId/route'
import { Route as ProtectedClassroomsClassroomIdIndexImport } from './routes/_protected/classrooms/$classroomId/index'
import { Route as ProtectedClassroomsClassroomIdSettingsImport } from './routes/_protected/classrooms/$classroomId/settings'
import { Route as ProtectedChaptersChapterIdPracticeImport } from './routes/_protected/chapters/$chapterId.practice'
import { Route as ProtectedChaptersChapterIdEditImport } from './routes/_protected/chapters/$chapterId.edit'

// Create/Update Routes

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedTestRoute = ProtectedTestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedSettingsRoute = ProtectedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedFocusSessionRoute = ProtectedFocusSessionImport.update({
  id: '/focus-session',
  path: '/focus-session',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDemoRoute = ProtectedDemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedCollectionRoute = ProtectedCollectionImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)

const ProtectedClassroomsIndexRoute = ProtectedClassroomsIndexImport.update({
  id: '/classrooms/',
  path: '/classrooms/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedChaptersIndexRoute = ProtectedChaptersIndexImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedClassroomsClassroomIdRouteRoute =
  ProtectedClassroomsClassroomIdRouteImport.update({
    id: '/classrooms/$classroomId',
    path: '/classrooms/$classroomId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

const ProtectedClassroomsClassroomIdIndexRoute =
  ProtectedClassroomsClassroomIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedClassroomsClassroomIdRouteRoute,
  } as any)

const ProtectedClassroomsClassroomIdSettingsRoute =
  ProtectedClassroomsClassroomIdSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedClassroomsClassroomIdRouteRoute,
  } as any)

const ProtectedChaptersChapterIdPracticeRoute =
  ProtectedChaptersChapterIdPracticeImport.update({
    id: '/chapters/$chapterId/practice',
    path: '/chapters/$chapterId/practice',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

const ProtectedChaptersChapterIdEditRoute =
  ProtectedChaptersChapterIdEditImport.update({
    id: '/chapters/$chapterId/edit',
    path: '/chapters/$chapterId/edit',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthRouteImport
    }
    '/_protected/collection': {
      id: '/_protected/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof ProtectedCollectionImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/demo': {
      id: '/_protected/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof ProtectedDemoImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/focus-session': {
      id: '/_protected/focus-session'
      path: '/focus-session'
      fullPath: '/focus-session'
      preLoaderRoute: typeof ProtectedFocusSessionImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/test': {
      id: '/_protected/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof ProtectedTestImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/classrooms/$classroomId': {
      id: '/_protected/classrooms/$classroomId'
      path: '/classrooms/$classroomId'
      fullPath: '/classrooms/$classroomId'
      preLoaderRoute: typeof ProtectedClassroomsClassroomIdRouteImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/chapters/': {
      id: '/_protected/chapters/'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ProtectedChaptersIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/classrooms/': {
      id: '/_protected/classrooms/'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ProtectedClassroomsIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/chapters/$chapterId/edit': {
      id: '/_protected/chapters/$chapterId/edit'
      path: '/chapters/$chapterId/edit'
      fullPath: '/chapters/$chapterId/edit'
      preLoaderRoute: typeof ProtectedChaptersChapterIdEditImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/chapters/$chapterId/practice': {
      id: '/_protected/chapters/$chapterId/practice'
      path: '/chapters/$chapterId/practice'
      fullPath: '/chapters/$chapterId/practice'
      preLoaderRoute: typeof ProtectedChaptersChapterIdPracticeImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/classrooms/$classroomId/settings': {
      id: '/_protected/classrooms/$classroomId/settings'
      path: '/settings'
      fullPath: '/classrooms/$classroomId/settings'
      preLoaderRoute: typeof ProtectedClassroomsClassroomIdSettingsImport
      parentRoute: typeof ProtectedClassroomsClassroomIdRouteImport
    }
    '/_protected/classrooms/$classroomId/': {
      id: '/_protected/classrooms/$classroomId/'
      path: '/'
      fullPath: '/classrooms/$classroomId/'
      preLoaderRoute: typeof ProtectedClassroomsClassroomIdIndexImport
      parentRoute: typeof ProtectedClassroomsClassroomIdRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedClassroomsClassroomIdRouteRouteChildren {
  ProtectedClassroomsClassroomIdSettingsRoute: typeof ProtectedClassroomsClassroomIdSettingsRoute
  ProtectedClassroomsClassroomIdIndexRoute: typeof ProtectedClassroomsClassroomIdIndexRoute
}

const ProtectedClassroomsClassroomIdRouteRouteChildren: ProtectedClassroomsClassroomIdRouteRouteChildren =
  {
    ProtectedClassroomsClassroomIdSettingsRoute:
      ProtectedClassroomsClassroomIdSettingsRoute,
    ProtectedClassroomsClassroomIdIndexRoute:
      ProtectedClassroomsClassroomIdIndexRoute,
  }

const ProtectedClassroomsClassroomIdRouteRouteWithChildren =
  ProtectedClassroomsClassroomIdRouteRoute._addFileChildren(
    ProtectedClassroomsClassroomIdRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedCollectionRoute: typeof ProtectedCollectionRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDemoRoute: typeof ProtectedDemoRoute
  ProtectedFocusSessionRoute: typeof ProtectedFocusSessionRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTestRoute: typeof ProtectedTestRoute
  ProtectedClassroomsClassroomIdRouteRoute: typeof ProtectedClassroomsClassroomIdRouteRouteWithChildren
  ProtectedChaptersIndexRoute: typeof ProtectedChaptersIndexRoute
  ProtectedClassroomsIndexRoute: typeof ProtectedClassroomsIndexRoute
  ProtectedChaptersChapterIdEditRoute: typeof ProtectedChaptersChapterIdEditRoute
  ProtectedChaptersChapterIdPracticeRoute: typeof ProtectedChaptersChapterIdPracticeRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCollectionRoute: ProtectedCollectionRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDemoRoute: ProtectedDemoRoute,
  ProtectedFocusSessionRoute: ProtectedFocusSessionRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTestRoute: ProtectedTestRoute,
  ProtectedClassroomsClassroomIdRouteRoute:
    ProtectedClassroomsClassroomIdRouteRouteWithChildren,
  ProtectedChaptersIndexRoute: ProtectedChaptersIndexRoute,
  ProtectedClassroomsIndexRoute: ProtectedClassroomsIndexRoute,
  ProtectedChaptersChapterIdEditRoute: ProtectedChaptersChapterIdEditRoute,
  ProtectedChaptersChapterIdPracticeRoute:
    ProtectedChaptersChapterIdPracticeRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/collection': typeof ProtectedCollectionRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/demo': typeof ProtectedDemoRoute
  '/focus-session': typeof ProtectedFocusSessionRoute
  '/settings': typeof ProtectedSettingsRoute
  '/test': typeof ProtectedTestRoute
  '/classrooms/$classroomId': typeof ProtectedClassroomsClassroomIdRouteRouteWithChildren
  '/chapters': typeof ProtectedChaptersIndexRoute
  '/classrooms': typeof ProtectedClassroomsIndexRoute
  '/chapters/$chapterId/edit': typeof ProtectedChaptersChapterIdEditRoute
  '/chapters/$chapterId/practice': typeof ProtectedChaptersChapterIdPracticeRoute
  '/classrooms/$classroomId/settings': typeof ProtectedClassroomsClassroomIdSettingsRoute
  '/classrooms/$classroomId/': typeof ProtectedClassroomsClassroomIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/collection': typeof ProtectedCollectionRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/demo': typeof ProtectedDemoRoute
  '/focus-session': typeof ProtectedFocusSessionRoute
  '/settings': typeof ProtectedSettingsRoute
  '/test': typeof ProtectedTestRoute
  '/chapters': typeof ProtectedChaptersIndexRoute
  '/classrooms': typeof ProtectedClassroomsIndexRoute
  '/chapters/$chapterId/edit': typeof ProtectedChaptersChapterIdEditRoute
  '/chapters/$chapterId/practice': typeof ProtectedChaptersChapterIdPracticeRoute
  '/classrooms/$classroomId/settings': typeof ProtectedClassroomsClassroomIdSettingsRoute
  '/classrooms/$classroomId': typeof ProtectedClassroomsClassroomIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/collection': typeof ProtectedCollectionRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/demo': typeof ProtectedDemoRoute
  '/_protected/focus-session': typeof ProtectedFocusSessionRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/test': typeof ProtectedTestRoute
  '/_protected/classrooms/$classroomId': typeof ProtectedClassroomsClassroomIdRouteRouteWithChildren
  '/_protected/chapters/': typeof ProtectedChaptersIndexRoute
  '/_protected/classrooms/': typeof ProtectedClassroomsIndexRoute
  '/_protected/chapters/$chapterId/edit': typeof ProtectedChaptersChapterIdEditRoute
  '/_protected/chapters/$chapterId/practice': typeof ProtectedChaptersChapterIdPracticeRoute
  '/_protected/classrooms/$classroomId/settings': typeof ProtectedClassroomsClassroomIdSettingsRoute
  '/_protected/classrooms/$classroomId/': typeof ProtectedClassroomsClassroomIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/collection'
    | '/dashboard'
    | '/demo'
    | '/focus-session'
    | '/settings'
    | '/test'
    | '/classrooms/$classroomId'
    | '/chapters'
    | '/classrooms'
    | '/chapters/$chapterId/edit'
    | '/chapters/$chapterId/practice'
    | '/classrooms/$classroomId/settings'
    | '/classrooms/$classroomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/collection'
    | '/dashboard'
    | '/demo'
    | '/focus-session'
    | '/settings'
    | '/test'
    | '/chapters'
    | '/classrooms'
    | '/chapters/$chapterId/edit'
    | '/chapters/$chapterId/practice'
    | '/classrooms/$classroomId/settings'
    | '/classrooms/$classroomId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/collection'
    | '/_protected/dashboard'
    | '/_protected/demo'
    | '/_protected/focus-session'
    | '/_protected/settings'
    | '/_protected/test'
    | '/_protected/classrooms/$classroomId'
    | '/_protected/chapters/'
    | '/_protected/classrooms/'
    | '/_protected/chapters/$chapterId/edit'
    | '/_protected/chapters/$chapterId/practice'
    | '/_protected/classrooms/$classroomId/settings'
    | '/_protected/classrooms/$classroomId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_protected"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/sign-in",
        "/_auth/sign-up"
      ]
    },
    "/_protected": {
      "filePath": "_protected/route.tsx",
      "children": [
        "/_protected/collection",
        "/_protected/dashboard",
        "/_protected/demo",
        "/_protected/focus-session",
        "/_protected/settings",
        "/_protected/test",
        "/_protected/classrooms/$classroomId",
        "/_protected/chapters/",
        "/_protected/classrooms/",
        "/_protected/chapters/$chapterId/edit",
        "/_protected/chapters/$chapterId/practice"
      ]
    },
    "/_auth/sign-in": {
      "filePath": "_auth/sign-in.tsx",
      "parent": "/_auth"
    },
    "/_auth/sign-up": {
      "filePath": "_auth/sign-up.tsx",
      "parent": "/_auth"
    },
    "/_protected/collection": {
      "filePath": "_protected/collection.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard": {
      "filePath": "_protected/dashboard.tsx",
      "parent": "/_protected"
    },
    "/_protected/demo": {
      "filePath": "_protected/demo.tsx",
      "parent": "/_protected"
    },
    "/_protected/focus-session": {
      "filePath": "_protected/focus-session.tsx",
      "parent": "/_protected"
    },
    "/_protected/settings": {
      "filePath": "_protected/settings.tsx",
      "parent": "/_protected"
    },
    "/_protected/test": {
      "filePath": "_protected/test.tsx",
      "parent": "/_protected"
    },
    "/_protected/classrooms/$classroomId": {
      "filePath": "_protected/classrooms/$classroomId/route.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/classrooms/$classroomId/settings",
        "/_protected/classrooms/$classroomId/"
      ]
    },
    "/_protected/chapters/": {
      "filePath": "_protected/chapters/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/classrooms/": {
      "filePath": "_protected/classrooms/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/chapters/$chapterId/edit": {
      "filePath": "_protected/chapters/$chapterId.edit.tsx",
      "parent": "/_protected"
    },
    "/_protected/chapters/$chapterId/practice": {
      "filePath": "_protected/chapters/$chapterId.practice.tsx",
      "parent": "/_protected"
    },
    "/_protected/classrooms/$classroomId/settings": {
      "filePath": "_protected/classrooms/$classroomId/settings.tsx",
      "parent": "/_protected/classrooms/$classroomId"
    },
    "/_protected/classrooms/$classroomId/": {
      "filePath": "_protected/classrooms/$classroomId/index.tsx",
      "parent": "/_protected/classrooms/$classroomId"
    }
  }
}
ROUTE_MANIFEST_END */
