/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedTestImport } from './routes/_protected/test'
import { Route as ProtectedFocusSessionImport } from './routes/_protected/focus-session'
import { Route as ProtectedDemoImport } from './routes/_protected/demo'
import { Route as ProtectedDashboardImport } from './routes/_protected/dashboard'
import { Route as ProtectedCollectionImport } from './routes/_protected/collection'
import { Route as ProtectedClassroomsImport } from './routes/_protected/classrooms'
import { Route as ProtectedChaptersImport } from './routes/_protected/chapters'
import { Route as AuthSignUpImport } from './routes/_auth/sign-up'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'

// Create/Update Routes

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedTestRoute = ProtectedTestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedFocusSessionRoute = ProtectedFocusSessionImport.update({
  id: '/focus-session',
  path: '/focus-session',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDemoRoute = ProtectedDemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedCollectionRoute = ProtectedCollectionImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedClassroomsRoute = ProtectedClassroomsImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedChaptersRoute = ProtectedChaptersImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthRouteImport
    }
    '/_protected/chapters': {
      id: '/_protected/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ProtectedChaptersImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/classrooms': {
      id: '/_protected/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ProtectedClassroomsImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/collection': {
      id: '/_protected/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof ProtectedCollectionImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/demo': {
      id: '/_protected/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof ProtectedDemoImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/focus-session': {
      id: '/_protected/focus-session'
      path: '/focus-session'
      fullPath: '/focus-session'
      preLoaderRoute: typeof ProtectedFocusSessionImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/test': {
      id: '/_protected/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof ProtectedTestImport
      parentRoute: typeof ProtectedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedChaptersRoute: typeof ProtectedChaptersRoute
  ProtectedClassroomsRoute: typeof ProtectedClassroomsRoute
  ProtectedCollectionRoute: typeof ProtectedCollectionRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDemoRoute: typeof ProtectedDemoRoute
  ProtectedFocusSessionRoute: typeof ProtectedFocusSessionRoute
  ProtectedTestRoute: typeof ProtectedTestRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedChaptersRoute: ProtectedChaptersRoute,
  ProtectedClassroomsRoute: ProtectedClassroomsRoute,
  ProtectedCollectionRoute: ProtectedCollectionRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDemoRoute: ProtectedDemoRoute,
  ProtectedFocusSessionRoute: ProtectedFocusSessionRoute,
  ProtectedTestRoute: ProtectedTestRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/chapters': typeof ProtectedChaptersRoute
  '/classrooms': typeof ProtectedClassroomsRoute
  '/collection': typeof ProtectedCollectionRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/demo': typeof ProtectedDemoRoute
  '/focus-session': typeof ProtectedFocusSessionRoute
  '/test': typeof ProtectedTestRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/chapters': typeof ProtectedChaptersRoute
  '/classrooms': typeof ProtectedClassroomsRoute
  '/collection': typeof ProtectedCollectionRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/demo': typeof ProtectedDemoRoute
  '/focus-session': typeof ProtectedFocusSessionRoute
  '/test': typeof ProtectedTestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/chapters': typeof ProtectedChaptersRoute
  '/_protected/classrooms': typeof ProtectedClassroomsRoute
  '/_protected/collection': typeof ProtectedCollectionRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/demo': typeof ProtectedDemoRoute
  '/_protected/focus-session': typeof ProtectedFocusSessionRoute
  '/_protected/test': typeof ProtectedTestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/chapters'
    | '/classrooms'
    | '/collection'
    | '/dashboard'
    | '/demo'
    | '/focus-session'
    | '/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/chapters'
    | '/classrooms'
    | '/collection'
    | '/dashboard'
    | '/demo'
    | '/focus-session'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/chapters'
    | '/_protected/classrooms'
    | '/_protected/collection'
    | '/_protected/dashboard'
    | '/_protected/demo'
    | '/_protected/focus-session'
    | '/_protected/test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_protected"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/sign-in",
        "/_auth/sign-up"
      ]
    },
    "/_protected": {
      "filePath": "_protected/route.tsx",
      "children": [
        "/_protected/chapters",
        "/_protected/classrooms",
        "/_protected/collection",
        "/_protected/dashboard",
        "/_protected/demo",
        "/_protected/focus-session",
        "/_protected/test"
      ]
    },
    "/_auth/sign-in": {
      "filePath": "_auth/sign-in.tsx",
      "parent": "/_auth"
    },
    "/_auth/sign-up": {
      "filePath": "_auth/sign-up.tsx",
      "parent": "/_auth"
    },
    "/_protected/chapters": {
      "filePath": "_protected/chapters.tsx",
      "parent": "/_protected"
    },
    "/_protected/classrooms": {
      "filePath": "_protected/classrooms.tsx",
      "parent": "/_protected"
    },
    "/_protected/collection": {
      "filePath": "_protected/collection.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard": {
      "filePath": "_protected/dashboard.tsx",
      "parent": "/_protected"
    },
    "/_protected/demo": {
      "filePath": "_protected/demo.tsx",
      "parent": "/_protected"
    },
    "/_protected/focus-session": {
      "filePath": "_protected/focus-session.tsx",
      "parent": "/_protected"
    },
    "/_protected/test": {
      "filePath": "_protected/test.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
